### ISSUE TITLE
Simplify Text Syntax

### ISSUE THREAD

**Issue by technobulb** [ouidevelop/text-message-directions#2]
First of all thanks for a great service!

I have a small issue. The word "for" is unnecessary. Weather 11223 works well for humans too. It makes more sense, is more fluid, and is more like the old 4info and google.sms that we are used to. Lets remove the extra word! (or make it optional)

Side question. Does the directions take live traffic into account?

**Comment by mKurrels** [comment]
> First of all thanks for a great service!
> 
> I have a small issue. The word "for" is unnecessary. Weather 11223 works well for humans too. It makes more sense, is more fluid, and is more like the old 4info and google.sms that we are used to. Lets remove the extra word! (or make it optional)
> 
> Side question. Does the directions take live traffic into account?

Ya not a bad suggestion. We can do that here soon.

The directions are taken from the google maps api, and I believe they do take traffic into account.

**Comment by mKurrels** [comment]
done!

**Comment by technobulb** [comment]
great thank you!
