### ISSUE TITLE
Software lacks a license

### ISSUE THREAD

**Issue by semioticrobotic** [ouidevelop/text-message-directions#3]
Thanks for offering this service!

How is this software licensed? An explicit statement of licensing conditions in a `LICENSE` file would be useful for resolving any ambiguity.

**Comment by mKurrels** [comment]
> Thanks for offering this service!
> 
> How is this software licensed? An explicit statement of licensing conditions in a `LICENSE` file would be useful for resolving any ambiguity.

Do you have any advice on what kind of license to add? Or any resources I should look at to make that decision?

**Comment by semioticrobotic** [comment]
Absolutely! I recommend starting with resources right here on GitHub, such as the [license chooser](https://choosealicense.com/).

**Comment by mKurrels** [comment]
> Absolutely! I recommend starting with resources right here on GitHub, such as the [license chooser](https://choosealicense.com/).

Thanks for the suggestion. Added an MIT license. 

Did you suggest this because you wanted to use the code? Or just general advice?

**Comment by semioticrobotic** [comment]
> Did you suggest this because you wanted to use the code? Or just general advice?

This is great news! Thank you!

I asked because I prefer to use and contribute to open source software, but when I reviewed your codebase I couldn't be certain it was open source. The explicit licensing statement helps clarify that. Additionally, while I am not a developer, I would like to do what I can to contribute to this project in the future, as I use it frequently and want to see it grow and thrive. But because the software lacked a license, I was ensure of the terms under which the project was accepting patches. Now I feel more confident contributing.

Thank you!
